### ISSUE TITLE
Error Imagen EO5

### ISSUE THREAD

**Issue by mgutierrezc** [DanielaVLl/meds_segundo#2]
![error_imagen_E05](https://user-images.githubusercontent.com/43623521/94072525-744aeb00-fdbb-11ea-96e0-2820dfb885be.png)

**Comment by verduralegorica** [comment]
Hola Marcos! En nuestras computadoras se logra visualizar todas las imágenes correctamente. Revisé el código y se llama a la imagen de la misma manera que en E01-E04, sabes a qué podría deberse?

![imagenes](https://user-images.githubusercontent.com/69405719/94072385-2cc45f00-fdbb-11ea-9a43-7830a8dce123.jpeg)

**Comment by mgutierrezc** [comment]
Lo que causó el error fue que subieron sus archivos como `.PNG` y no `.png`. Los nombres de sus archivos nunca deben tener sus extensiones en minúscula porque el servidor distingue entre mayus y minus. Para cualquier modificacion que planeen hacer a su codigo, no hagan algo asi otra vez y cualquier cosa que vayan a añadir **siempre** debe estar en **minuscula**
